### ISSUE TITLE
请问有什么办法处理图和图的覆盖层级问题吗？

### ISSUE THREAD

**Issue by co-star** [wg-front/wxml2canvas#1]
![image](https://user-images.githubusercontent.com/21311900/53626030-9ca25000-3c3f-11e9-877f-d405e11d7ccc.png)

**Comment by co-star** [comment]
试过，背景图和图，都失败了，看源码是按左到右渲染的，有涉及层级的设计吗

**Comment by wg-front** [comment]
wxml节点上设置data-delay="1" (取值1-100)，可以实现层级控制，实际上是按值的大小setTimeout延迟绘制。

**Comment by co-star** [comment]
> wxml节点上设置data-delay="1" (取值1-100)，可以实现层级控制，实际上是按值的大小setTimeout延迟绘制。

好的

**Comment by co-star** [comment]
> wxml节点上设置data-delay="1" (取值1-100)，可以实现层级控制，实际上是按值的大小setTimeout延迟绘制。

还有一个就是精度调整，在真机上会很模糊，有什么方法调整吗
