### ISSUE TITLE
数据配置方式绘制图片，无法缩放吗？

### ISSUE THREAD

**Issue by tower1229** [wg-front/wxml2canvas#2]
目前绘制图片的配置项只有绘制区域的width和height，没有针对图片缩放的配置吗？

**Comment by wg-front** [comment]
配置数据里设置的宽高、坐标都是以iphone6的375宽为基准计算的，不同的机型会自动计算适配。

**Comment by tower1229** [comment]
我是指图片裁剪、缩放的模式，对应image组件的mode属性

**Comment by wg-front** [comment]
下一版本会支持裁剪
