### ISSUE TITLE
三星s10出现data-type="text"绘制数字不显示的问题

### ISSUE THREAD

**Issue by co-star** [wg-front/wxml2canvas#7]
![image](https://user-images.githubusercontent.com/21311900/55867056-52a07880-5bb4-11e9-8f7c-955dc9288f71.png)
![image](https://user-images.githubusercontent.com/21311900/55867195-9c895e80-5bb4-11e9-85e6-e4ef992fd685.png)
其他机型正常

**Comment by ttylikl** [comment]
data-text的内容如果是数字，在安卓微信的某些版本上会遇到不能substring的问题。可以检查一下data-text的类型，是否确实是text

**Comment by co-star** [comment]
已解决，感谢🙏
